post:
  max_title: 250
  min_title: 6
  min_content: 6
  extension:
    hot_question: "hot_question"
    recent_comment: "recent_comment"
comment:
  object_type:
    post: "post"
    answer: "answer"
topic:
  q_a: "1"
  feedback: "2"
  confesstion: "3"
  type_sort:
    recently: "newest"
    popular: "popular"
    recently_answer: "recently_answer"
    no_answer: "no_answer"
anonymous: "1"
max_search_tags: 5
plus_one: 1
paginate_offset: 1
paginate_default: 4
paginate_tags: 20
paginate_users: 6
id_user_hiddent: 1
content_max_length: 500
limit_top: 3
limit_tag: 5
pictures:
  accepted_files: "image/jpeg, image/gif, image/png"
reaction_type:
  up: "upvote"
  down: "downvote"
  like: "like"
  dislike: "dislike"
  heart: "heart"
success: "success"
error: "error"
activities:
  items_per_page: 10
relationships:
  follow: "follow"
  unfollow: "unfollow"
limit_string:
  content: 200
  name: 50
